### ISSUE TITLE
Missing WorkingDirectory parameter on Systemd::Unit::Service

### ISSUE THREAD

**Issue by hboetes** [voxpupuli/puppet-systemd#320] opened 2023-02-23 17:13 UTC
Hi there,

I just tried to generate a systemd file and got the message that `WorkingDirectory=` and `User=` were unknown options for the service section, so I added them in `types/unit/service.pp`, like so:

```puppet
    Optional['WorkingDirectory']          => String,
    Optional['User']                      => String,
```

After things worked fine again. But… am I missing something or are those options really missing. They are documented: https://www.freedesktop.org/software/systemd/man/systemd.exec.html

Thanks!

**Comment by kenyon** [comment] 2023-02-23 17:24
As said in #288 

> Not every systemd directive has been added but a healthy set has and subsequents can be added as required.

**Comment by smortex** [comment] 2023-02-23 23:49
:wave: @hboetes 

Please send these changes as a Pull-Request :wink:

**Comment by jhoblitt** [comment] 2023-03-01 16:38
Related to #321

**Comment by ekohl** [comment] 2023-03-20 21:06
Closing as duplicate of #299

**Comment by ekohl** [comment] 2023-03-21 13:06
Actually going to reopen this and scope it down to just `WorkingDirectory`.

**Comment by traylenator** [comment] 2023-06-23 07:14
WorkingDirectory was added in c785f4fc2803bfaf3bd2ccc67a952a048000cc3c

**Closed by traylenator** 2023-06-23 07:14 UTC
Labels: enhancement
