### ISSUE TITLE
Dependency cycle when systemd types are declared in different subclasses

### ISSUE THREAD

**Issue by stdietrich** [voxpupuli/puppet-systemd#300] opened 2022-11-04 14:14 UTC
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.17.0
- Ruby: 2.7.6p219
- Distribution: AlmaLinux 8
- Module version: 3.10.0

## How to reproduce (e.g Puppet code you use)

If you use the `systemd` types provided by this module and use it in different subclasses of a module, you'll end up in dependency cycles.
The pre-requisite is, that you 2 systemd resources try to manage the same systemd service, e.g. a drop-in file for service A and configuring the unit file for service A as well:

```puppet
# declare class
include my_module

# init.pp - my_module
class my_module {
  contain my_module::config
  contain my_module::service

  Class['my_module::config']
  -> Class['my_module::service']
}

# config.pp
class my_module::config {
  systemd::dropin_file {'extra.conf':
    unit => 'myservice.service',
    content => 'does not matter',
  }
}

# service.pp
class my_module::service {
  systemd::unit_file {'myservice.service':
    content => 'does not matter',
  }
}
```

You can copy/paste this snippet to a single file and test the code via `puppet apply`:
`puppet apply --verbose test.pp`

The same issue can be observed by replacing `systemd::unit_file` with another `systemd::dropin_file`

## What are you seeing

What you'll receive, is a dependency cycle:
```
(Exec[systemd-myservice.service-systemctl-daemon-reload] => Systemd::Daemon_reload[myservice.service] => Systemd::Dropin_file[extra.conf] => Class[My_module::Config] => Class[My_module::Service] => Systemd::Unit_file[myservice.service] => File[/etc/systemd/system/myservice.service] => Systemd::Daemon_reload[myservice.service] => Exec[systemd-myservice.service-systemctl-daemon-reload])\nTry the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
```

This happens with any resource, which uses the daemon reload mechanism. The only workaround is to change the code, e.g. colocate both systemd resource in a single subclass, or set `daemon_reload => false` on a single resource.

## What behaviour did you expect instead

No dependency cycle.
I discovered this issue after upgrading from camptocamp-systemd 2.2.0 -> puppet-systemd 3.10.0, with the old camptocamp-systemd module this issue was not present.

## Output log

See above.

## Any additional information you'd like to impart

To fix this for `systemd::dropin_file`, I think it would be sufficient to change the [ensure_resource](https://github.com/voxpupuli/puppet-systemd/blob/1d785f129b5b5395860b1d39723e0aa7b31f7c74/manifests/dropin_file.pp#L75) from `$unit` to `$name`

`ensure_resource('systemd::daemon_reload', $unit)` -> `ensure_resource('systemd::daemon_reload', $name)`

This results into unique `systemd::daemon_reload` resources and the dependency cycle is gone. However, it is now called twice for the same unit.

Would be happy to fix this with some code, but would love to hear some additional opinions beforehand.

**Comment by stdietrich** [comment] 2022-11-04 15:07
Please note, while #286 looks similar, it is IMHO a slightly different problem.

**Comment by jhoblitt** [comment] 2023-01-27 16:20
I suspect the only way around this is if `systemd::dropin_file` would not notify `Systemd::Daemon_reload[$unit]` or `Service <| title == $unit or name == $unit |>` and instead notified the related `systemd::unit_file`.

**Comment by jhoblitt** [comment] 2023-01-27 16:33
I'm going to close this as a duplicate of https://github.com/voxpupuli/puppet-systemd/issues/286.  In #286, the reported issue is the dropin_file requiring the unit_file. This issue is inverse of the unit_file requiring the dropin_file.

**Closed by jhoblitt** 2023-01-27 16:33 UTC
Labels: duplicate
